[package]
name = "chip8_bevy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = {version = "0.9"}
bevy_egui = "0.17"
lazy_static = "1.4.0"
sdl2 = "0.35.2"
